package Vista;

import Controlador.ControladorUsuario;
import Modelo.Usuario;
import javax.swing.JOptionPane;

public class FrmLogin extends javax.swing.JFrame {

  /**
   * Creates new form FrmLogin
   */
  public FrmLogin() {
    initComponents();

    // Configurar cierre
    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

    // Agregar listener para cuando se cierre
    addWindowListener(new java.awt.event.WindowAdapter() {
      @Override
      public void windowClosing(java.awt.event.WindowEvent e) {
        confirmarSalida();
      }
    });

  }

  private void confirmarSalida() {
    int opcion = JOptionPane.showConfirmDialog(this,
            "¿Está seguro que desea salir del sistema?",
            "Confirmar salida",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.QUESTION_MESSAGE);

    if (opcion == JOptionPane.YES_OPTION) {
      // Cerrar esta ventana
      this.dispose();

      // Si quieres volver al login en lugar de salir:
      //new FrmLogin().setVisible(true);
      // O salir completamente:
      System.exit(0);
    }
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    panelDetras = new javax.swing.JSplitPane();
    panelIzquierdo = new javax.swing.JPanel();
    panaderia = new javax.swing.JLabel();
    eslogan = new javax.swing.JLabel();
    panelDerecho = new javax.swing.JPanel();
    usuario = new javax.swing.JLabel();
    contraseña = new javax.swing.JLabel();
    campoUsuario = new javax.swing.JTextField();
    campoPassword = new javax.swing.JPasswordField();
    botonIniciar = new javax.swing.JButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    panelDetras.setResizeWeight(0.5);

    panelIzquierdo.setBackground(new java.awt.Color(255, 153, 255));

    panaderia.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
    panaderia.setForeground(new java.awt.Color(51, 51, 51));
    panaderia.setText("PANADERIA");
    panaderia.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

    eslogan.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 18)); // NOI18N
    eslogan.setForeground(new java.awt.Color(51, 51, 51));
    eslogan.setText("La Mas Riquisima");
    eslogan.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

    javax.swing.GroupLayout panelIzquierdoLayout = new javax.swing.GroupLayout(panelIzquierdo);
    panelIzquierdo.setLayout(panelIzquierdoLayout);
    panelIzquierdoLayout.setHorizontalGroup(
      panelIzquierdoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(panelIzquierdoLayout.createSequentialGroup()
        .addGap(58, 58, 58)
        .addGroup(panelIzquierdoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
          .addComponent(eslogan)
          .addComponent(panaderia))
        .addContainerGap(39, Short.MAX_VALUE))
    );
    panelIzquierdoLayout.setVerticalGroup(
      panelIzquierdoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(panelIzquierdoLayout.createSequentialGroup()
        .addGap(143, 143, 143)
        .addComponent(panaderia)
        .addGap(44, 44, 44)
        .addComponent(eslogan)
        .addContainerGap(151, Short.MAX_VALUE))
    );

    panelDetras.setLeftComponent(panelIzquierdo);

    panelDerecho.setForeground(new java.awt.Color(255, 255, 255));

    usuario.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
    usuario.setText("Usuario");

    contraseña.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
    contraseña.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    contraseña.setText("Contraseña");

    campoUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
      public void keyPressed(java.awt.event.KeyEvent evt) {
        campoUsuarioKeyPressed(evt);
      }
    });

    campoPassword.addKeyListener(new java.awt.event.KeyAdapter() {
      public void keyPressed(java.awt.event.KeyEvent evt) {
        campoPasswordKeyPressed(evt);
      }
    });

    botonIniciar.setBackground(new java.awt.Color(255, 153, 255));
    botonIniciar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
    botonIniciar.setForeground(new java.awt.Color(51, 51, 51));
    botonIniciar.setText("Inicias Sesion ");
    botonIniciar.setActionCommand("Iniciar");
    botonIniciar.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        botonIniciarActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout panelDerechoLayout = new javax.swing.GroupLayout(panelDerecho);
    panelDerecho.setLayout(panelDerechoLayout);
    panelDerechoLayout.setHorizontalGroup(
      panelDerechoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(panelDerechoLayout.createSequentialGroup()
        .addGroup(panelDerechoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(panelDerechoLayout.createSequentialGroup()
            .addGap(18, 18, 18)
            .addComponent(contraseña))
          .addGroup(panelDerechoLayout.createSequentialGroup()
            .addGap(30, 30, 30)
            .addComponent(usuario)))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addGroup(panelDerechoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
          .addComponent(campoPassword)
          .addComponent(campoUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 245, Short.MAX_VALUE)
          .addGroup(panelDerechoLayout.createSequentialGroup()
            .addGap(11, 11, 11)
            .addComponent(botonIniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)))
        .addContainerGap(73, Short.MAX_VALUE))
    );
    panelDerechoLayout.setVerticalGroup(
      panelDerechoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(panelDerechoLayout.createSequentialGroup()
        .addGap(210, 210, 210)
        .addGroup(panelDerechoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(usuario)
          .addComponent(campoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(37, 37, 37)
        .addGroup(panelDerechoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(contraseña)
          .addComponent(campoPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(18, 18, 18)
        .addComponent(botonIniciar)
        .addContainerGap(54, Short.MAX_VALUE))
    );

    panelDetras.setRightComponent(panelDerecho);

    getContentPane().add(panelDetras, java.awt.BorderLayout.CENTER);

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void botonIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonIniciarActionPerformed
    this.Login();
  }//GEN-LAST:event_botonIniciarActionPerformed

  private void campoUsuarioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoUsuarioKeyPressed
    if (evt.getKeyCode() == evt.VK_ENTER) {
      campoPassword.requestFocus();
    }
  }//GEN-LAST:event_campoUsuarioKeyPressed

  private void campoPasswordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoPasswordKeyPressed
    if (evt.getKeyCode() == evt.VK_ENTER) {
      this.Login();
    }
  }//GEN-LAST:event_campoPasswordKeyPressed


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton botonIniciar;
  private javax.swing.JPasswordField campoPassword;
  private javax.swing.JTextField campoUsuario;
  private javax.swing.JLabel contraseña;
  private javax.swing.JLabel eslogan;
  private javax.swing.JLabel panaderia;
  private javax.swing.JPanel panelDerecho;
  private javax.swing.JSplitPane panelDetras;
  private javax.swing.JPanel panelIzquierdo;
  private javax.swing.JLabel usuario;
  // End of variables declaration//GEN-END:variables

//login
  private void Login() {
    // Validar campos
    String usernameText = campoUsuario.getText().trim();
    char[] passwordChars = campoPassword.getPassword();
    String passwordText = new String(passwordChars).trim();

    if (usernameText.isEmpty() || passwordText.isEmpty()) {
      JOptionPane.showMessageDialog(this, "Ingrese usuario y contraseña");
      return;
    }

    try {
      int idEmpleado = Integer.parseInt(usernameText);

      ControladorUsuario controlUsuario = new ControladorUsuario();
      Usuario usuario = new Usuario();
      usuario.setId_Empleado(idEmpleado);
      usuario.setPassword(passwordText);

      if (controlUsuario.loginUser(usuario)) {
        // Login exitoso

        // Ocultar esta ventana
        this.setVisible(false);

        // Crear y mostrar ventana principal
        java.awt.EventQueue.invokeLater(() -> {
          FrmMenu menu = new FrmMenu();
          menu.setLocationRelativeTo(null); // Centrar
          menu.setVisible(true);

          // Cuando la principal se cierra, cerrar también el login
          menu.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosed(java.awt.event.WindowEvent e) {
              // Cerrar completamente la aplicación
              System.exit(0);
            }
          });
        });

      } else {
        JOptionPane.showMessageDialog(this, "Credenciales incorrectas");
        campoPassword.setText("");
      }

    } catch (NumberFormatException e) {
      JOptionPane.showMessageDialog(this, "El ID debe ser un número");
    } finally {
      // Limpiar contraseña en memoria
      java.util.Arrays.fill(passwordChars, '0');
    }
  }
}
