package Vista;

import java.awt.Color;
import java.awt.Dimension;
import javax.swing.JDesktopPane;


public class FrmMenu extends javax.swing.JFrame {
  
  public static JDesktopPane jDesktopPane_menu;
  public FrmMenu() {
    initComponents();
    this.setSize(new Dimension(900, 600));
    this.setExtendedState(this.MAXIMIZED_BOTH);
    this.setLocationRelativeTo(null);
    this.setTitle("Sistema Panaderia");
    
    this.setLayout(null);
    jDesktopPane_menu = new JDesktopPane();
    jDesktopPane_menu.setBackground(new Color(30, 144, 255)); // Azul Dodger
    
    int ancho = java.awt.Toolkit.getDefaultToolkit().getScreenSize().width;
    int alto = java.awt.Toolkit.getDefaultToolkit().getScreenSize().height;
    this.jDesktopPane_menu.setBounds(0, 0, ancho, (alto-110));
    this.add(jDesktopPane_menu);
    
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jMenuBar1 = new javax.swing.JMenuBar();
    menuProductos = new javax.swing.JMenu();
    jMenuItem3 = new javax.swing.JMenuItem();
    jMenuItem5 = new javax.swing.JMenuItem();
    menuClientes = new javax.swing.JMenu();
    jMenuItem6 = new javax.swing.JMenuItem();
    jMenuItem7 = new javax.swing.JMenuItem();
    menuCompras = new javax.swing.JMenu();
    nuevaCompra = new javax.swing.JMenuItem();
    menuVentas = new javax.swing.JMenu();
    nuevaVenta = new javax.swing.JMenuItem();
    menuInventario = new javax.swing.JMenu();
    verInventario = new javax.swing.JMenuItem();
    menuProveedores = new javax.swing.JMenu();
    jMenuItem15 = new javax.swing.JMenuItem();
    menuProduccion = new javax.swing.JMenu();
    jMenuItem16 = new javax.swing.JMenuItem();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    menuProductos.setText("Productos");
    menuProductos.setPreferredSize(new java.awt.Dimension(90, 40));

    jMenuItem3.setText("Nuevo Producto");
    menuProductos.add(jMenuItem3);

    jMenuItem5.setText("Actualizar Stock");
    menuProductos.add(jMenuItem5);

    jMenuBar1.add(menuProductos);

    menuClientes.setText("Clientes");
    menuClientes.setPreferredSize(new java.awt.Dimension(90, 40));

    jMenuItem6.setText("Nuevo Cliente");
    menuClientes.add(jMenuItem6);

    jMenuItem7.setText("Gestionar Clientes");
    menuClientes.add(jMenuItem7);

    jMenuBar1.add(menuClientes);

    menuCompras.setText("Compras");
    menuCompras.setPreferredSize(new java.awt.Dimension(90, 40));

    nuevaCompra.setText("Nueva Compra");
    nuevaCompra.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        nuevaCompraActionPerformed(evt);
      }
    });
    menuCompras.add(nuevaCompra);

    jMenuBar1.add(menuCompras);

    menuVentas.setText("Ventas");
    menuVentas.setToolTipText("");
    menuVentas.setPreferredSize(new java.awt.Dimension(90, 40));

    nuevaVenta.setText("Nueva Venta");
    nuevaVenta.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        nuevaVentaActionPerformed(evt);
      }
    });
    menuVentas.add(nuevaVenta);

    jMenuBar1.add(menuVentas);

    menuInventario.setText("Inventario");
    menuInventario.setPreferredSize(new java.awt.Dimension(90, 40));

    verInventario.setText("Ver Inventario");
    verInventario.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        verInventarioActionPerformed(evt);
      }
    });
    menuInventario.add(verInventario);

    jMenuBar1.add(menuInventario);

    menuProveedores.setText("Proveedores");
    menuProveedores.setPreferredSize(new java.awt.Dimension(90, 40));

    jMenuItem15.setText("Nuevo Proveedor");
    menuProveedores.add(jMenuItem15);

    jMenuBar1.add(menuProveedores);

    menuProduccion.setText("Produccion");
    menuProduccion.setPreferredSize(new java.awt.Dimension(90, 40));

    jMenuItem16.setText("Gestionar Produccion");
    menuProduccion.add(jMenuItem16);

    jMenuBar1.add(menuProduccion);

    setJMenuBar(jMenuBar1);

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void verInventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verInventarioActionPerformed
    InterInventario interInventario = new InterInventario();
    jDesktopPane_menu.add(interInventario);
    interInventario.setVisible(true);
  }//GEN-LAST:event_verInventarioActionPerformed

  private void nuevaCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevaCompraActionPerformed
    InterCompras interCompras = new InterCompras();
    jDesktopPane_menu.add(interCompras);
    interCompras.setVisible(true);
  }//GEN-LAST:event_nuevaCompraActionPerformed

  private void nuevaVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevaVentaActionPerformed
    InterVentas interVentas = new InterVentas();
    jDesktopPane_menu.add(interVentas);
    interVentas.setVisible(true);
  }//GEN-LAST:event_nuevaVentaActionPerformed

  

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JMenuBar jMenuBar1;
  private javax.swing.JMenuItem jMenuItem15;
  private javax.swing.JMenuItem jMenuItem16;
  private javax.swing.JMenuItem jMenuItem3;
  private javax.swing.JMenuItem jMenuItem5;
  private javax.swing.JMenuItem jMenuItem6;
  private javax.swing.JMenuItem jMenuItem7;
  private javax.swing.JMenu menuClientes;
  private javax.swing.JMenu menuCompras;
  private javax.swing.JMenu menuInventario;
  private javax.swing.JMenu menuProduccion;
  private javax.swing.JMenu menuProductos;
  private javax.swing.JMenu menuProveedores;
  private javax.swing.JMenu menuVentas;
  private javax.swing.JMenuItem nuevaCompra;
  private javax.swing.JMenuItem nuevaVenta;
  private javax.swing.JMenuItem verInventario;
  // End of variables declaration//GEN-END:variables
}
