package Vista;

import Controlador.ControladorInventario;
import java.awt.Dimension;
import javax.swing.JOptionPane;

public class InterInventario extends javax.swing.JInternalFrame {

  public InterInventario() {
    initComponents();
    this.setSize(new Dimension(400, 200));
    this.setTitle("Ver Inventario");

  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    tituloInventario = new javax.swing.JLabel();
    textoNombre = new javax.swing.JLabel();
    campoNombre = new javax.swing.JTextField();
    botonBuscar = new javax.swing.JButton();

    setClosable(true);
    setIconifiable(true);
    setResizable(true);
    getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    tituloInventario.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
    tituloInventario.setText("Inventario");
    getContentPane().add(tituloInventario, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 0, -1, -1));

    textoNombre.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
    textoNombre.setText("Nombre de Materia Prima");
    getContentPane().add(textoNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));
    getContentPane().add(campoNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 40, 170, -1));

    botonBuscar.setText("Buscar");
    botonBuscar.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        botonBuscarActionPerformed(evt);
      }
    });
    getContentPane().add(botonBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, 90, 30));

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void botonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBuscarActionPerformed
    try {
      String nombre = campoNombre.getText().trim(); // Cambia el nombre del campo
      if (nombre.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Ingrese un nombre");
        return;
      }

      ControladorInventario controlador = new ControladorInventario();
      Modelo.Inventario resultado = controlador.buscarPorNombre(nombre);

      if (resultado != null) {
        javax.swing.JOptionPane.showMessageDialog(this,
                "Encontrado: " + resultado.getNombre()
                + "\nID Inventario: " + resultado.getId_inventario() // Mostrar el ID
                + "\nNumero de Compra: " + resultado.getId_compra()
                + "\nCantidad: " + resultado.getCantidad_disponible()
                + " " + resultado.getUnidad_medida()
                + "\nPrecio: $" + resultado.getPrecio());
      } else {
        JOptionPane.showMessageDialog(this,
                "No se encontró: " + nombre);
      }
    } catch (Exception e) {
      JOptionPane.showMessageDialog(this,
              "Error: " + e.getMessage());
    }
  }//GEN-LAST:event_botonBuscarActionPerformed


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton botonBuscar;
  private javax.swing.JTextField campoNombre;
  private javax.swing.JLabel textoNombre;
  private javax.swing.JLabel tituloInventario;
  // End of variables declaration//GEN-END:variables
}
