package Vista;

import Controlador.ControladorInventario;
import java.awt.Dimension;

public class InterInventario extends javax.swing.JInternalFrame {


  public InterInventario() {
    initComponents();
    this.setSize(new Dimension(400, 200));
    this.setTitle("Ver Inventario");

  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    tituloInventario = new javax.swing.JLabel();
    textoNum = new javax.swing.JLabel();
    campoId = new javax.swing.JTextField();
    botonBuscar = new javax.swing.JButton();

    setClosable(true);
    setIconifiable(true);
    setResizable(true);
    getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    tituloInventario.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
    tituloInventario.setText("Inventario");
    getContentPane().add(tituloInventario, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 0, -1, -1));

    textoNum.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
    textoNum.setText("Numero de Inventario");
    getContentPane().add(textoNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, -1));
    getContentPane().add(campoId, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 40, 170, -1));

    botonBuscar.setText("Buscar");
    botonBuscar.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        botonBuscarActionPerformed(evt);
      }
    });
    getContentPane().add(botonBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, 90, 30));

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void botonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBuscarActionPerformed
    try {
      String idTexto = campoId.getText().trim();
      if (idTexto.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "Ingrese un ID");
        return;
      }

      int id = Integer.parseInt(idTexto);
      ControladorInventario controlador = new ControladorInventario();
      Modelo.Inventario resultado = controlador.buscarId(id);

      if (resultado != null) {
        javax.swing.JOptionPane.showMessageDialog(this,
                "Encontrado: " + resultado.getNombre()
                + "\nNumero de Compra " + resultado.getId_compra()
                + "\nCantidad: " + resultado.getCantidad_disponible()
                + resultado.getUnidad_medida()
                + "\nPrecio: $" + resultado.getPrecio());
      } else {
        javax.swing.JOptionPane.showMessageDialog(this,
                "No se encontró ID: " + id);
      }

    } catch (Exception e) {
      javax.swing.JOptionPane.showMessageDialog(this,
              "Error: " + e.getMessage());
    }


  }//GEN-LAST:event_botonBuscarActionPerformed


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton botonBuscar;
  private javax.swing.JTextField campoId;
  private javax.swing.JLabel textoNum;
  private javax.swing.JLabel tituloInventario;
  // End of variables declaration//GEN-END:variables
}
